DATASETS:
  PATH: "data/syntesized_data/nsl_kdd.csv"
  DATA_TYPE: "nsl_kdd"
  TASK: "classification"
  BATCH_SIZE: 1024
  N_CLASSES: 5
  REDUCE: False
  LATENT_DIM: 3
  REDUCE_WEIGHT_PATH: "weights/autoencoder/nsl_kdd8192_128_24.pt"
MODEL:
  NAME: "tab_transformer"
  INPUT_EMBED_DIM: 32
  EMBEDDING_DROPOUT: 0.1
  SHARE_EMBEDDING_STRATEGY: "add"
  SHARED_EMBEDDING_FRACTION: 0.25
  NUM_ATT_BLOCKS: 12
  NUM_HEADS: 8
  FF_HIDDEN_MULTIPLIER: 4
  TRANSFORMER_ACTIVATION: "GEGLU"
  ATTN_DROPOUT: 0.1
  FF_DROPOUT: 0.1
  ADD_NORM_DROPOUT: 0.1
  BATCH_NORM_CONTINUOUS_INPUT: False
  OUT_FF_LAYERS: [256, 128, 64, 32]
  OUT_FF_ACTIVATION: "ReLU"
  OUT_FF_INITIALIZATION: "kaiming"
  USE_BATCH_NORM: False
  OUT_FF_DROPOUT: 0.0
TRAIN:
  SCHEME: 2
  BETA: 0.7
  MARGIN: 0.2
  EPOCHS: 200
  LR: 3e-4
  WEIGHT_DECAY: 1e-3
  WEIGHT_PATH: "weights/final_model"